### ISSUE TITLE
<div> cannot appear as a descendant of <p>.

### ISSUE THREAD

**Issue by kesteinbakk** [coreyward/react-portable-text#13]
I get the following two warnings when using react-portable-text:

```
> Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
>     at p
>     at block (webpack-internal:///./node_modules/react-portable-text/dist/index.js:1:3129)
>     at BlockSerializer (webpack-internal:///./node_modules/react-portable-text/node_modules/@sanity/block-content-to-hyperscript/lib/serializers.js:14:22)
>     at div
>     at SanityBlockContent (webpack-internal:///./node_modules/react-portable-text/node_modules/@sanity/block-content-to-react/lib/BlockContent.js:19:89)
>     at v (webpack-internal:///./node_modules/react-portable-text/dist/index.js:1:1215)

```
and:

```
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
>     at div
>     at SanityBlockContent (webpack-internal:///./node_modules/react-portable-text/node_modules/@sanity/block-content-to-react/lib/BlockContent.js:19:89)
>     at v (webpack-internal:///./node_modules/react-portable-text/dist/index.js:1:1215)
```

I am using react-portable-text as follows:
```
<PortableText
  // Passing in block content straight from Sanity.io
  content={_rawBody}
  projectId={process.env.SANITY_PROJECT_ID}
  dataset={process.env.SANITY_DATASET}
/>
```
My content is just plan text with some line breaks. 

Any suggestions on how to avoid the warning?

**Comment by coreyward** [comment]
Without seeing either the input (`_rawBody`) or output JSX it's a bit hard to diagnose, but I suspect this is a case where the issue lies with something other than this library. Perhaps you have something like the following happening?

```jsx
<p>
  <PortableText {…props} />
</p>
```
